import type { HorarioDia, Sucursal } from "./types"

const horarioEstandar: HorarioDia[] = [
  { dia: "Lunes", apertura: "09:00", cierre: "19:00" },
  { dia: "Martes", apertura: "09:00", cierre: "19:00" },
  { dia: "Miércoles", apertura: "09:00", cierre: "19:00" },
  { dia: "Jueves", apertura: "09:00", cierre: "19:00" },
  { dia: "Viernes", apertura: "09:00", cierre: "19:00" },
  { dia: "Sábado", apertura: "10:00", cierre: "14:00" },
  { dia: "Domingo", apertura: "Cerrado", cierre: "Cerrado" },
]

export const sucursales: Sucursal[] = [
  {
    id: "br-1",
    nombre: "Starken Santiago Centro 1",
    direccion: "Av. Principal 917, Santiago Centro",
    comuna: "Santiago Centro",
    region: "Región Metropolitana",
    lat: -33.4654,
    lng: -70.6797,
    tipo: "24/7",
    estado: "cerrado",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 5008 3512",
  },
  {
    id: "br-2",
    nombre: "Starken Santiago Centro 2",
    direccion: "Av. Principal 34, Santiago Centro",
    comuna: "Santiago Centro",
    region: "Región Metropolitana",
    lat: -33.4486,
    lng: -70.6679,
    tipo: "tradicional",
    estado: "abierto",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 8046 1239",
  },
  {
    id: "br-3",
    nombre: "Starken Santiago Centro 3",
    direccion: "Av. Principal 739, Santiago Centro",
    comuna: "Santiago Centro",
    region: "Región Metropolitana",
    lat: -33.4576,
    lng: -70.6581,
    tipo: "tradicional",
    estado: "cerrado",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 6892 3677",
  },
  {
    id: "br-4",
    nombre: "Starken Santiago Centro 4",
    direccion: "Av. Principal 434, Santiago Centro",
    comuna: "Santiago Centro",
    region: "Región Metropolitana",
    lat: -33.4527,
    lng: -70.6623,
    tipo: "tradicional",
    estado: "abierto",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 1675 8408",
  },
  {
    id: "br-5",
    nombre: "Starken Santiago Centro 5",
    direccion: "Av. Principal 545, Santiago Centro",
    comuna: "Santiago Centro",
    region: "Región Metropolitana",
    lat: -33.4328,
    lng: -70.6812,
    tipo: "24/7",
    estado: "con_retraso",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 6685 2566",
  },
  {
    id: "br-6",
    nombre: "Starken Santiago Centro 6",
    direccion: "Av. Principal 969, Santiago Centro",
    comuna: "Santiago Centro",
    region: "Región Metropolitana",
    lat: -33.4591,
    lng: -70.6754,
    tipo: "red-alianzas",
    estado: "cerrado",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 1541 5896",
  },
  {
    id: "br-7",
    nombre: "Starken Santiago Centro 7",
    direccion: "Av. Principal 271, Santiago Centro",
    comuna: "Santiago Centro",
    region: "Región Metropolitana",
    lat: -33.4671,
    lng: -70.6697,
    tipo: "24/7",
    estado: "abierto",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 3634 8584",
  },
  {
    id: "br-8",
    nombre: "Starken Santiago Centro 8",
    direccion: "Av. Principal 541, Santiago Centro",
    comuna: "Santiago Centro",
    region: "Región Metropolitana",
    lat: -33.4422,
    lng: -70.6665,
    tipo: "red-alianzas",
    estado: "abierto",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 1036 1314",
  },
  {
    id: "br-9",
    nombre: "Starken Santiago Centro 9",
    direccion: "Av. Principal 124, Santiago Centro",
    comuna: "Santiago Centro",
    region: "Región Metropolitana",
    lat: -33.4448,
    lng: -70.6652,
    tipo: "tradicional",
    estado: "cerrado",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 5127 7483",
  },
  {
    id: "br-10",
    nombre: "Starken Santiago Centro 10",
    direccion: "Av. Principal 566, Santiago Centro",
    comuna: "Santiago Centro",
    region: "Región Metropolitana",
    lat: -33.4653,
    lng: -70.6639,
    tipo: "soy-starken",
    estado: "con_retraso",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 3326 5839",
  },
  {
    id: "br-11",
    nombre: "Starken Santiago Centro 11",
    direccion: "Av. Principal 322, Santiago Centro",
    comuna: "Santiago Centro",
    region: "Región Metropolitana",
    lat: -33.4645,
    lng: -70.6762,
    tipo: "24/7",
    estado: "cerrado",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 1048 7783",
  },
  {
    id: "br-12",
    nombre: "Starken Santiago Centro 12",
    direccion: "Av. Principal 24, Santiago Centro",
    comuna: "Santiago Centro",
    region: "Región Metropolitana",
    lat: -33.4651,
    lng: -70.6690,
    tipo: "tradicional",
    estado: "con_retraso",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 3720 4854",
  },
  {
    id: "br-13",
    nombre: "Starken Santiago Centro 13",
    direccion: "Av. Principal 111, Santiago Centro",
    comuna: "Santiago Centro",
    region: "Región Metropolitana",
    lat: -33.4427,
    lng: -70.6558,
    tipo: "tradicional",
    estado: "cerrado",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 1071 1126",
  },
  {
    id: "br-14",
    nombre: "Starken Santiago Centro 14",
    direccion: "Av. Principal 216, Santiago Centro",
    comuna: "Santiago Centro",
    region: "Región Metropolitana",
    lat: -33.4468,
    lng: -70.6600,
    tipo: "24/7",
    estado: "cerrado",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 1261 8358",
  },
  {
    id: "br-15",
    nombre: "Starken Santiago Centro 15",
    direccion: "Av. Principal 688, Santiago Centro",
    comuna: "Santiago Centro",
    region: "Región Metropolitana",
    lat: -33.4686,
    lng: -70.6764,
    tipo: "red-alianzas",
    estado: "abierto",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 6163 3404",
  },
  {
    id: "br-16",
    nombre: "Starken Providencia 1",
    direccion: "Av. Principal 962, Providencia",
    comuna: "Providencia",
    region: "Región Metropolitana",
    lat: -33.4509,
    lng: -70.5939,
    tipo: "tradicional",
    estado: "con_retraso",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 4130 2953",
  },
  {
    id: "br-17",
    nombre: "Starken Providencia 2",
    direccion: "Av. Principal 624, Providencia",
    comuna: "Providencia",
    region: "Región Metropolitana",
    lat: -33.4487,
    lng: -70.6017,
    tipo: "red-alianzas",
    estado: "con_retraso",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 2235 6280",
  },
  {
    id: "br-18",
    nombre: "Starken Providencia 3",
    direccion: "Av. Principal 626, Providencia",
    comuna: "Providencia",
    region: "Región Metropolitana",
    lat: -33.4161,
    lng: -70.6313,
    tipo: "tradicional",
    estado: "con_retraso",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 4941 2727",
  },
  {
    id: "br-19",
    nombre: "Starken Providencia 4",
    direccion: "Av. Principal 299, Providencia",
    comuna: "Providencia",
    region: "Región Metropolitana",
    lat: -33.4144,
    lng: -70.6048,
    tipo: "soy-starken",
    estado: "abierto",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 5283 7054",
  },
  {
    id: "br-20",
    nombre: "Starken Providencia 5",
    direccion: "Av. Principal 674, Providencia",
    comuna: "Providencia",
    region: "Región Metropolitana",
    lat: -33.4451,
    lng: -70.6187,
    tipo: "red-alianzas",
    estado: "con_retraso",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 9504 7931",
  },
  {
    id: "br-21",
    nombre: "Starken Providencia 6",
    direccion: "Av. Principal 324, Providencia",
    comuna: "Providencia",
    region: "Región Metropolitana",
    lat: -33.4333,
    lng: -70.6299,
    tipo: "tradicional",
    estado: "cerrado",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 9565 2280",
  },
  {
    id: "br-22",
    nombre: "Starken Providencia 7",
    direccion: "Av. Principal 620, Providencia",
    comuna: "Providencia",
    region: "Región Metropolitana",
    lat: -33.4272,
    lng: -70.6313,
    tipo: "tradicional",
    estado: "con_retraso",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 1852 6954",
  },
  {
    id: "br-23",
    nombre: "Starken Providencia 8",
    direccion: "Av. Principal 585, Providencia",
    comuna: "Providencia",
    region: "Región Metropolitana",
    lat: -33.4409,
    lng: -70.5952,
    tipo: "red-alianzas",
    estado: "con_retraso",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 9105 9416",
  },
  {
    id: "br-24",
    nombre: "Starken Providencia 9",
    direccion: "Av. Principal 10, Providencia",
    comuna: "Providencia",
    region: "Región Metropolitana",
    lat: -33.4212,
    lng: -70.5945,
    tipo: "red-alianzas",
    estado: "con_retraso",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 6967 1294",
  },
  {
    id: "br-25",
    nombre: "Starken Providencia 10",
    direccion: "Av. Principal 86, Providencia",
    comuna: "Providencia",
    region: "Región Metropolitana",
    lat: -33.4144,
    lng: -70.6143,
    tipo: "tradicional",
    estado: "con_retraso",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 1573 6535",
  },
  {
    id: "br-26",
    nombre: "Starken Providencia 11",
    direccion: "Av. Principal 608, Providencia",
    comuna: "Providencia",
    region: "Región Metropolitana",
    lat: -33.4398,
    lng: -70.5985,
    tipo: "24/7",
    estado: "cerrado",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 8002 3165",
  },
  {
    id: "br-27",
    nombre: "Starken Providencia 12",
    direccion: "Av. Principal 243, Providencia",
    comuna: "Providencia",
    region: "Región Metropolitana",
    lat: -33.4345,
    lng: -70.6128,
    tipo: "soy-starken",
    estado: "con_retraso",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 9654 3737",
  },
  {
    id: "br-28",
    nombre: "Starken Providencia 13",
    direccion: "Av. Principal 691, Providencia",
    comuna: "Providencia",
    region: "Región Metropolitana",
    lat: -33.4186,
    lng: -70.5926,
    tipo: "red-alianzas",
    estado: "con_retraso",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 8997 1127",
  },
  {
    id: "br-29",
    nombre: "Starken Providencia 14",
    direccion: "Av. Principal 373, Providencia",
    comuna: "Providencia",
    region: "Región Metropolitana",
    lat: -33.4517,
    lng: -70.6220,
    tipo: "red-alianzas",
    estado: "cerrado",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 1555 2021",
  },
  {
    id: "br-30",
    nombre: "Starken Providencia 15",
    direccion: "Av. Principal 493, Providencia",
    comuna: "Providencia",
    region: "Región Metropolitana",
    lat: -33.4504,
    lng: -70.6316,
    tipo: "24/7",
    estado: "con_retraso",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 5426 1901",
  },
  {
    id: "br-31",
    nombre: "Starken Las Condes 1",
    direccion: "Av. Principal 544, Las Condes",
    comuna: "Las Condes",
    region: "Región Metropolitana",
    lat: -33.4101,
    lng: -70.5535,
    tipo: "soy-starken",
    estado: "cerrado",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 8640 2514",
  },
  {
    id: "br-32",
    nombre: "Starken Las Condes 2",
    direccion: "Av. Principal 647, Las Condes",
    comuna: "Las Condes",
    region: "Región Metropolitana",
    lat: -33.4259,
    lng: -70.5874,
    tipo: "tradicional",
    estado: "abierto",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 3471 8844",
  },
  {
    id: "br-33",
    nombre: "Starken Las Condes 3",
    direccion: "Av. Principal 806, Las Condes",
    comuna: "Las Condes",
    region: "Región Metropolitana",
    lat: -33.4079,
    lng: -70.5772,
    tipo: "tradicional",
    estado: "con_retraso",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 8295 1746",
  },
  {
    id: "br-34",
    nombre: "Starken Las Condes 4",
    direccion: "Av. Principal 596, Las Condes",
    comuna: "Las Condes",
    region: "Región Metropolitana",
    lat: -33.4289,
    lng: -70.5704,
    tipo: "tradicional",
    estado: "con_retraso",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 4050 2854",
  },
  {
    id: "br-35",
    nombre: "Starken Las Condes 5",
    direccion: "Av. Principal 157, Las Condes",
    comuna: "Las Condes",
    region: "Región Metropolitana",
    lat: -33.4050,
    lng: -70.5559,
    tipo: "tradicional",
    estado: "cerrado",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 6382 8921",
  },
  {
    id: "br-36",
    nombre: "Starken Las Condes 6",
    direccion: "Av. Principal 780, Las Condes",
    comuna: "Las Condes",
    region: "Región Metropolitana",
    lat: -33.3947,
    lng: -70.5597,
    tipo: "tradicional",
    estado: "cerrado",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 9347 4134",
  },
  {
    id: "br-37",
    nombre: "Starken Las Condes 7",
    direccion: "Av. Principal 187, Las Condes",
    comuna: "Las Condes",
    region: "Región Metropolitana",
    lat: -33.4181,
    lng: -70.5842,
    tipo: "soy-starken",
    estado: "con_retraso",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 7161 8151",
  },
  {
    id: "br-38",
    nombre: "Starken Las Condes 8",
    direccion: "Av. Principal 579, Las Condes",
    comuna: "Las Condes",
    region: "Región Metropolitana",
    lat: -33.4263,
    lng: -70.5711,
    tipo: "24/7",
    estado: "cerrado",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 5240 6019",
  },
  {
    id: "br-39",
    nombre: "Starken Las Condes 9",
    direccion: "Av. Principal 491, Las Condes",
    comuna: "Las Condes",
    region: "Región Metropolitana",
    lat: -33.3917,
    lng: -70.5773,
    tipo: "soy-starken",
    estado: "cerrado",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 4129 1449",
  },
  {
    id: "br-40",
    nombre: "Starken Las Condes 10",
    direccion: "Av. Principal 511, Las Condes",
    comuna: "Las Condes",
    region: "Región Metropolitana",
    lat: -33.4058,
    lng: -70.5873,
    tipo: "24/7",
    estado: "abierto",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 4159 3633",
  },
  {
    id: "br-41",
    nombre: "Starken Las Condes 11",
    direccion: "Av. Principal 613, Las Condes",
    comuna: "Las Condes",
    region: "Región Metropolitana",
    lat: -33.4028,
    lng: -70.5602,
    tipo: "tradicional",
    estado: "cerrado",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 2933 6499",
  },
  {
    id: "br-42",
    nombre: "Starken Las Condes 12",
    direccion: "Av. Principal 351, Las Condes",
    comuna: "Las Condes",
    region: "Región Metropolitana",
    lat: -33.3980,
    lng: -70.5621,
    tipo: "soy-starken",
    estado: "abierto",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 6901 4992",
  },
  {
    id: "br-43",
    nombre: "Starken Las Condes 13",
    direccion: "Av. Principal 764, Las Condes",
    comuna: "Las Condes",
    region: "Región Metropolitana",
    lat: -33.4004,
    lng: -70.5623,
    tipo: "24/7",
    estado: "cerrado",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 4328 7712",
  },
  {
    id: "br-44",
    nombre: "Starken Las Condes 14",
    direccion: "Av. Principal 471, Las Condes",
    comuna: "Las Condes",
    region: "Región Metropolitana",
    lat: -33.4237,
    lng: -70.5495,
    tipo: "24/7",
    estado: "cerrado",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 2472 7322",
  },
  {
    id: "br-45",
    nombre: "Starken Las Condes 15",
    direccion: "Av. Principal 860, Las Condes",
    comuna: "Las Condes",
    region: "Región Metropolitana",
    lat: -33.4106,
    lng: -70.5660,
    tipo: "soy-starken",
    estado: "abierto",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 8834 3802",
  },
  {
    id: "br-46",
    nombre: "Starken Maipú 1",
    direccion: "Av. Principal 91, Maipú",
    comuna: "Maipú",
    region: "Región Metropolitana",
    lat: -33.5206,
    lng: -70.7581,
    tipo: "tradicional",
    estado: "cerrado",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 1756 7979",
  },
  {
    id: "br-47",
    nombre: "Starken Maipú 2",
    direccion: "Av. Principal 164, Maipú",
    comuna: "Maipú",
    region: "Región Metropolitana",
    lat: -33.5109,
    lng: -70.7641,
    tipo: "24/7",
    estado: "cerrado",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 3687 3871",
  },
  {
    id: "br-48",
    nombre: "Starken Maipú 3",
    direccion: "Av. Principal 539, Maipú",
    comuna: "Maipú",
    region: "Región Metropolitana",
    lat: -33.5184,
    lng: -70.7760,
    tipo: "soy-starken",
    estado: "con_retraso",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 8797 2799",
  },
  {
    id: "br-49",
    nombre: "Starken Maipú 4",
    direccion: "Av. Principal 741, Maipú",
    comuna: "Maipú",
    region: "Región Metropolitana",
    lat: -33.5283,
    lng: -70.7646,
    tipo: "24/7",
    estado: "con_retraso",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 7700 1823",
  },
  {
    id: "br-50",
    nombre: "Starken Maipú 5",
    direccion: "Av. Principal 580, Maipú",
    comuna: "Maipú",
    region: "Región Metropolitana",
    lat: -33.5352,
    lng: -70.7714,
    tipo: "tradicional",
    estado: "con_retraso",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 4803 9368",
  },
  {
    id: "br-51",
    nombre: "Starken Maipú 6",
    direccion: "Av. Principal 948, Maipú",
    comuna: "Maipú",
    region: "Región Metropolitana",
    lat: -33.5167,
    lng: -70.7724,
    tipo: "tradicional",
    estado: "abierto",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 5565 4932",
  },
  {
    id: "br-52",
    nombre: "Starken Maipú 7",
    direccion: "Av. Principal 779, Maipú",
    comuna: "Maipú",
    region: "Región Metropolitana",
    lat: -33.5283,
    lng: -70.7789,
    tipo: "24/7",
    estado: "con_retraso",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 3479 1971",
  },
  {
    id: "br-53",
    nombre: "Starken Maipú 8",
    direccion: "Av. Principal 500, Maipú",
    comuna: "Maipú",
    region: "Región Metropolitana",
    lat: -33.5111,
    lng: -70.7492,
    tipo: "tradicional",
    estado: "cerrado",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 4843 4842",
  },
  {
    id: "br-54",
    nombre: "Starken Maipú 9",
    direccion: "Av. Principal 30, Maipú",
    comuna: "Maipú",
    region: "Región Metropolitana",
    lat: -33.5284,
    lng: -70.7463,
    tipo: "tradicional",
    estado: "abierto",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 9578 8049",
  },
  {
    id: "br-55",
    nombre: "Starken Maipú 10",
    direccion: "Av. Principal 362, Maipú",
    comuna: "Maipú",
    region: "Región Metropolitana",
    lat: -33.5319,
    lng: -70.7506,
    tipo: "tradicional",
    estado: "cerrado",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 2199 3168",
  },
  {
    id: "br-56",
    nombre: "Starken Maipú 11",
    direccion: "Av. Principal 59, Maipú",
    comuna: "Maipú",
    region: "Región Metropolitana",
    lat: -33.5228,
    lng: -70.7614,
    tipo: "red-alianzas",
    estado: "cerrado",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 5027 5660",
  },
  {
    id: "br-57",
    nombre: "Starken Maipú 12",
    direccion: "Av. Principal 573, Maipú",
    comuna: "Maipú",
    region: "Región Metropolitana",
    lat: -33.5042,
    lng: -70.7585,
    tipo: "soy-starken",
    estado: "con_retraso",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 2226 3435",
  },
  {
    id: "br-58",
    nombre: "Starken Maipú 13",
    direccion: "Av. Principal 368, Maipú",
    comuna: "Maipú",
    region: "Región Metropolitana",
    lat: -33.5112,
    lng: -70.7444,
    tipo: "24/7",
    estado: "abierto",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 9036 2497",
  },
  {
    id: "br-59",
    nombre: "Starken Maipú 14",
    direccion: "Av. Principal 519, Maipú",
    comuna: "Maipú",
    region: "Región Metropolitana",
    lat: -33.5100,
    lng: -70.7616,
    tipo: "soy-starken",
    estado: "abierto",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 2827 8389",
  },
  {
    id: "br-60",
    nombre: "Starken Maipú 15",
    direccion: "Av. Principal 813, Maipú",
    comuna: "Maipú",
    region: "Región Metropolitana",
    lat: -33.5093,
    lng: -70.7706,
    tipo: "24/7",
    estado: "con_retraso",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 4499 3210",
  },
  {
    id: "br-61",
    nombre: "Starken La Florida 1",
    direccion: "Av. Principal 837, La Florida",
    comuna: "La Florida",
    region: "Región Metropolitana",
    lat: -33.5257,
    lng: -70.6165,
    tipo: "red-alianzas",
    estado: "abierto",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 5629 9176",
  },
  {
    id: "br-62",
    nombre: "Starken La Florida 2",
    direccion: "Av. Principal 271, La Florida",
    comuna: "La Florida",
    region: "Región Metropolitana",
    lat: -33.5305,
    lng: -70.5786,
    tipo: "tradicional",
    estado: "abierto",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 1987 4464",
  },
  {
    id: "br-63",
    nombre: "Starken La Florida 3",
    direccion: "Av. Principal 977, La Florida",
    comuna: "La Florida",
    region: "Región Metropolitana",
    lat: -33.5249,
    lng: -70.5859,
    tipo: "soy-starken",
    estado: "cerrado",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 7440 4064",
  },
  {
    id: "br-64",
    nombre: "Starken La Florida 4",
    direccion: "Av. Principal 283, La Florida",
    comuna: "La Florida",
    region: "Región Metropolitana",
    lat: -33.5207,
    lng: -70.6031,
    tipo: "soy-starken",
    estado: "abierto",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 1920 6100",
  },
  {
    id: "br-65",
    nombre: "Starken La Florida 5",
    direccion: "Av. Principal 517, La Florida",
    comuna: "La Florida",
    region: "Región Metropolitana",
    lat: -33.5326,
    lng: -70.5908,
    tipo: "tradicional",
    estado: "con_retraso",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 2890 4312",
  },
  {
    id: "br-66",
    nombre: "Starken La Florida 6",
    direccion: "Av. Principal 632, La Florida",
    comuna: "La Florida",
    region: "Región Metropolitana",
    lat: -33.5285,
    lng: -70.5848,
    tipo: "soy-starken",
    estado: "cerrado",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 5216 5879",
  },
  {
    id: "br-67",
    nombre: "Starken La Florida 7",
    direccion: "Av. Principal 311, La Florida",
    comuna: "La Florida",
    region: "Región Metropolitana",
    lat: -33.5066,
    lng: -70.6037,
    tipo: "red-alianzas",
    estado: "con_retraso",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 1315 2465",
  },
  {
    id: "br-68",
    nombre: "Starken La Florida 8",
    direccion: "Av. Principal 126, La Florida",
    comuna: "La Florida",
    region: "Región Metropolitana",
    lat: -33.5024,
    lng: -70.5858,
    tipo: "soy-starken",
    estado: "abierto",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 9581 4691",
  },
  {
    id: "br-69",
    nombre: "Starken La Florida 9",
    direccion: "Av. Principal 282, La Florida",
    comuna: "La Florida",
    region: "Región Metropolitana",
    lat: -33.5402,
    lng: -70.6139,
    tipo: "24/7",
    estado: "con_retraso",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 5636 1745",
  },
  {
    id: "br-70",
    nombre: "Starken La Florida 10",
    direccion: "Av. Principal 698, La Florida",
    comuna: "La Florida",
    region: "Región Metropolitana",
    lat: -33.5216,
    lng: -70.6115,
    tipo: "soy-starken",
    estado: "abierto",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 1326 8911",
  },
  {
    id: "br-71",
    nombre: "Starken Puente Alto 1",
    direccion: "Av. Principal 641, Puente Alto",
    comuna: "Puente Alto",
    region: "Región Metropolitana",
    lat: -33.6089,
    lng: -70.5633,
    tipo: "24/7",
    estado: "con_retraso",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 2421 3408",
  },
  {
    id: "br-72",
    nombre: "Starken Puente Alto 2",
    direccion: "Av. Principal 0, Puente Alto",
    comuna: "Puente Alto",
    region: "Región Metropolitana",
    lat: -33.6002,
    lng: -70.5874,
    tipo: "tradicional",
    estado: "con_retraso",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 3579 4416",
  },
  {
    id: "br-73",
    nombre: "Starken Puente Alto 3",
    direccion: "Av. Principal 428, Puente Alto",
    comuna: "Puente Alto",
    region: "Región Metropolitana",
    lat: -33.6018,
    lng: -70.5694,
    tipo: "24/7",
    estado: "cerrado",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 2760 1075",
  },
  {
    id: "br-74",
    nombre: "Starken Puente Alto 4",
    direccion: "Av. Principal 963, Puente Alto",
    comuna: "Puente Alto",
    region: "Región Metropolitana",
    lat: -33.6131,
    lng: -70.5812,
    tipo: "soy-starken",
    estado: "cerrado",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 3898 1224",
  },
  {
    id: "br-75",
    nombre: "Starken Puente Alto 5",
    direccion: "Av. Principal 228, Puente Alto",
    comuna: "Puente Alto",
    region: "Región Metropolitana",
    lat: -33.6010,
    lng: -70.5588,
    tipo: "soy-starken",
    estado: "con_retraso",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 9514 4727",
  },
  {
    id: "br-76",
    nombre: "Starken Puente Alto 6",
    direccion: "Av. Principal 688, Puente Alto",
    comuna: "Puente Alto",
    region: "Región Metropolitana",
    lat: -33.6248,
    lng: -70.5575,
    tipo: "tradicional",
    estado: "con_retraso",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 7060 8019",
  },
  {
    id: "br-77",
    nombre: "Starken Puente Alto 7",
    direccion: "Av. Principal 312, Puente Alto",
    comuna: "Puente Alto",
    region: "Región Metropolitana",
    lat: -33.6021,
    lng: -70.5725,
    tipo: "red-alianzas",
    estado: "con_retraso",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 5448 9649",
  },
  {
    id: "br-78",
    nombre: "Starken Puente Alto 8",
    direccion: "Av. Principal 603, Puente Alto",
    comuna: "Puente Alto",
    region: "Región Metropolitana",
    lat: -33.6048,
    lng: -70.5910,
    tipo: "24/7",
    estado: "abierto",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 3057 1636",
  },
  {
    id: "br-79",
    nombre: "Starken Puente Alto 9",
    direccion: "Av. Principal 597, Puente Alto",
    comuna: "Puente Alto",
    region: "Región Metropolitana",
    lat: -33.5969,
    lng: -70.5609,
    tipo: "24/7",
    estado: "abierto",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 8367 6349",
  },
  {
    id: "br-80",
    nombre: "Starken Puente Alto 10",
    direccion: "Av. Principal 513, Puente Alto",
    comuna: "Puente Alto",
    region: "Región Metropolitana",
    lat: -33.5971,
    lng: -70.5938,
    tipo: "24/7",
    estado: "abierto",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 7911 2935",
  },
  {
    id: "br-81",
    nombre: "Starken Iquique 1",
    direccion: "Av. Principal 247, Iquique",
    comuna: "Iquique",
    region: "Regiones",
    lat: -20.2129,
    lng: -70.1357,
    tipo: "24/7",
    estado: "cerrado",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 3427 4535",
  },
  {
    id: "br-82",
    nombre: "Starken Iquique 2",
    direccion: "Av. Principal 565, Iquique",
    comuna: "Iquique",
    region: "Regiones",
    lat: -20.2079,
    lng: -70.1346,
    tipo: "soy-starken",
    estado: "abierto",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 6361 8967",
  },
  {
    id: "br-83",
    nombre: "Starken Iquique 3",
    direccion: "Av. Principal 295, Iquique",
    comuna: "Iquique",
    region: "Regiones",
    lat: -20.2190,
    lng: -70.1322,
    tipo: "tradicional",
    estado: "abierto",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 9722 3939",
  },
  {
    id: "br-84",
    nombre: "Starken Iquique 4",
    direccion: "Av. Principal 507, Iquique",
    comuna: "Iquique",
    region: "Regiones",
    lat: -20.2044,
    lng: -70.1573,
    tipo: "soy-starken",
    estado: "cerrado",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 8287 9038",
  },
  {
    id: "br-85",
    nombre: "Starken Antofagasta 1",
    direccion: "Av. Principal 515, Antofagasta",
    comuna: "Antofagasta",
    region: "Regiones",
    lat: -23.6433,
    lng: -70.4029,
    tipo: "tradicional",
    estado: "abierto",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 2135 1195",
  },
  {
    id: "br-86",
    nombre: "Starken Antofagasta 2",
    direccion: "Av. Principal 316, Antofagasta",
    comuna: "Antofagasta",
    region: "Regiones",
    lat: -23.6380,
    lng: -70.4089,
    tipo: "red-alianzas",
    estado: "con_retraso",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 8142 1394",
  },
  {
    id: "br-87",
    nombre: "Starken Antofagasta 3",
    direccion: "Av. Principal 156, Antofagasta",
    comuna: "Antofagasta",
    region: "Regiones",
    lat: -23.6442,
    lng: -70.4058,
    tipo: "soy-starken",
    estado: "cerrado",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 3290 4079",
  },
  {
    id: "br-88",
    nombre: "Starken Antofagasta 4",
    direccion: "Av. Principal 278, Antofagasta",
    comuna: "Antofagasta",
    region: "Regiones",
    lat: -23.6315,
    lng: -70.4103,
    tipo: "red-alianzas",
    estado: "abierto",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 6719 1457",
  },
  {
    id: "br-89",
    nombre: "Starken Antofagasta 5",
    direccion: "Av. Principal 249, Antofagasta",
    comuna: "Antofagasta",
    region: "Regiones",
    lat: -23.6357,
    lng: -70.4061,
    tipo: "tradicional",
    estado: "con_retraso",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 3715 8668",
  },
  {
    id: "br-90",
    nombre: "Starken La Serena 1",
    direccion: "Av. Principal 746, La Serena",
    comuna: "La Serena",
    region: "Regiones",
    lat: -29.9035,
    lng: -71.2355,
    tipo: "24/7",
    estado: "con_retraso",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 6126 6187",
  },
  {
    id: "br-91",
    nombre: "Starken La Serena 2",
    direccion: "Av. Principal 124, La Serena",
    comuna: "La Serena",
    region: "Regiones",
    lat: -29.8954,
    lng: -71.2507,
    tipo: "red-alianzas",
    estado: "abierto",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 6535 8302",
  },
  {
    id: "br-92",
    nombre: "Starken La Serena 3",
    direccion: "Av. Principal 361, La Serena",
    comuna: "La Serena",
    region: "Regiones",
    lat: -29.9142,
    lng: -71.2628,
    tipo: "24/7",
    estado: "cerrado",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 8525 5014",
  },
  {
    id: "br-93",
    nombre: "Starken La Serena 4",
    direccion: "Av. Principal 184, La Serena",
    comuna: "La Serena",
    region: "Regiones",
    lat: -29.9129,
    lng: -71.2439,
    tipo: "24/7",
    estado: "cerrado",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 5808 9713",
  },
  {
    id: "br-94",
    nombre: "Starken Valparaíso 1",
    direccion: "Av. Principal 355, Valparaíso",
    comuna: "Valparaíso",
    region: "Regiones",
    lat: -33.0334,
    lng: -71.6192,
    tipo: "tradicional",
    estado: "cerrado",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 8764 7739",
  },
  {
    id: "br-95",
    nombre: "Starken Valparaíso 2",
    direccion: "Av. Principal 244, Valparaíso",
    comuna: "Valparaíso",
    region: "Regiones",
    lat: -33.0499,
    lng: -71.6288,
    tipo: "24/7",
    estado: "con_retraso",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 9353 9736",
  },
  {
    id: "br-96",
    nombre: "Starken Valparaíso 3",
    direccion: "Av. Principal 313, Valparaíso",
    comuna: "Valparaíso",
    region: "Regiones",
    lat: -33.0329,
    lng: -71.6043,
    tipo: "red-alianzas",
    estado: "con_retraso",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 7718 4431",
  },
  {
    id: "br-97",
    nombre: "Starken Valparaíso 4",
    direccion: "Av. Principal 323, Valparaíso",
    comuna: "Valparaíso",
    region: "Regiones",
    lat: -33.0448,
    lng: -71.6184,
    tipo: "tradicional",
    estado: "con_retraso",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 8411 7905",
  },
  {
    id: "br-98",
    nombre: "Starken Valparaíso 5",
    direccion: "Av. Principal 331, Valparaíso",
    comuna: "Valparaíso",
    region: "Regiones",
    lat: -33.0351,
    lng: -71.6132,
    tipo: "soy-starken",
    estado: "cerrado",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 6364 6622",
  },
  {
    id: "br-99",
    nombre: "Starken Viña del Mar 1",
    direccion: "Av. Principal 141, Viña del Mar",
    comuna: "Viña del Mar",
    region: "Regiones",
    lat: -33.0221,
    lng: -71.5527,
    tipo: "24/7",
    estado: "cerrado",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 5758 5198",
  },
  {
    id: "br-100",
    nombre: "Starken Viña del Mar 2",
    direccion: "Av. Principal 725, Viña del Mar",
    comuna: "Viña del Mar",
    region: "Regiones",
    lat: -33.0263,
    lng: -71.5329,
    tipo: "tradicional",
    estado: "con_retraso",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 1162 3253",
  },
  {
    id: "br-101",
    nombre: "Starken Viña del Mar 3",
    direccion: "Av. Principal 471, Viña del Mar",
    comuna: "Viña del Mar",
    region: "Regiones",
    lat: -33.0381,
    lng: -71.5661,
    tipo: "tradicional",
    estado: "abierto",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 9890 5411",
  },
  {
    id: "br-102",
    nombre: "Starken Viña del Mar 4",
    direccion: "Av. Principal 938, Viña del Mar",
    comuna: "Viña del Mar",
    region: "Regiones",
    lat: -33.0158,
    lng: -71.5359,
    tipo: "24/7",
    estado: "cerrado",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 8339 9882",
  },
  {
    id: "br-103",
    nombre: "Starken Viña del Mar 5",
    direccion: "Av. Principal 350, Viña del Mar",
    comuna: "Viña del Mar",
    region: "Regiones",
    lat: -33.0126,
    lng: -71.5677,
    tipo: "red-alianzas",
    estado: "abierto",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 4577 7142",
  },
  {
    id: "br-104",
    nombre: "Starken Concepción 1",
    direccion: "Av. Principal 420, Concepción",
    comuna: "Concepción",
    region: "Regiones",
    lat: -36.8241,
    lng: -73.0549,
    tipo: "soy-starken",
    estado: "cerrado",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 5616 6739",
  },
  {
    id: "br-105",
    nombre: "Starken Concepción 2",
    direccion: "Av. Principal 51, Concepción",
    comuna: "Concepción",
    region: "Regiones",
    lat: -36.8283,
    lng: -73.0247,
    tipo: "soy-starken",
    estado: "con_retraso",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 2188 8955",
  },
  {
    id: "br-106",
    nombre: "Starken Concepción 3",
    direccion: "Av. Principal 284, Concepción",
    comuna: "Concepción",
    region: "Regiones",
    lat: -36.8068,
    lng: -73.0325,
    tipo: "soy-starken",
    estado: "cerrado",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 6131 5139",
  },
  {
    id: "br-107",
    nombre: "Starken Concepción 4",
    direccion: "Av. Principal 125, Concepción",
    comuna: "Concepción",
    region: "Regiones",
    lat: -36.8287,
    lng: -73.0466,
    tipo: "red-alianzas",
    estado: "abierto",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 1159 8921",
  },
  {
    id: "br-108",
    nombre: "Starken Concepción 5",
    direccion: "Av. Principal 943, Concepción",
    comuna: "Concepción",
    region: "Regiones",
    lat: -36.8083,
    lng: -73.0472,
    tipo: "24/7",
    estado: "cerrado",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 7303 7216",
  },
  {
    id: "br-109",
    nombre: "Starken Concepción 6",
    direccion: "Av. Principal 457, Concepción",
    comuna: "Concepción",
    region: "Regiones",
    lat: -36.8237,
    lng: -73.0383,
    tipo: "soy-starken",
    estado: "abierto",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 5661 9086",
  },
  {
    id: "br-110",
    nombre: "Starken Temuco 1",
    direccion: "Av. Principal 452, Temuco",
    comuna: "Temuco",
    region: "Regiones",
    lat: -38.7554,
    lng: -72.5799,
    tipo: "red-alianzas",
    estado: "abierto",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 2060 3080",
  },
  {
    id: "br-111",
    nombre: "Starken Temuco 2",
    direccion: "Av. Principal 65, Temuco",
    comuna: "Temuco",
    region: "Regiones",
    lat: -38.7546,
    lng: -72.6004,
    tipo: "tradicional",
    estado: "abierto",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 1020 2744",
  },
  {
    id: "br-112",
    nombre: "Starken Temuco 3",
    direccion: "Av. Principal 207, Temuco",
    comuna: "Temuco",
    region: "Regiones",
    lat: -38.7495,
    lng: -72.6093,
    tipo: "24/7",
    estado: "abierto",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 4572 5003",
  },
  {
    id: "br-113",
    nombre: "Starken Temuco 4",
    direccion: "Av. Principal 405, Temuco",
    comuna: "Temuco",
    region: "Regiones",
    lat: -38.7335,
    lng: -72.5813,
    tipo: "24/7",
    estado: "abierto",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 1302 3366",
  },
  {
    id: "br-114",
    nombre: "Starken Temuco 5",
    direccion: "Av. Principal 428, Temuco",
    comuna: "Temuco",
    region: "Regiones",
    lat: -38.7444,
    lng: -72.5918,
    tipo: "red-alianzas",
    estado: "cerrado",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 2122 2882",
  },
  {
    id: "br-115",
    nombre: "Starken Valdivia 1",
    direccion: "Av. Principal 959, Valdivia",
    comuna: "Valdivia",
    region: "Regiones",
    lat: -39.8138,
    lng: -73.2410,
    tipo: "red-alianzas",
    estado: "cerrado",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 5722 3732",
  },
  {
    id: "br-116",
    nombre: "Starken Valdivia 2",
    direccion: "Av. Principal 515, Valdivia",
    comuna: "Valdivia",
    region: "Regiones",
    lat: -39.8138,
    lng: -73.2374,
    tipo: "soy-starken",
    estado: "cerrado",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 9375 5479",
  },
  {
    id: "br-117",
    nombre: "Starken Valdivia 3",
    direccion: "Av. Principal 337, Valdivia",
    comuna: "Valdivia",
    region: "Regiones",
    lat: -39.8384,
    lng: -73.2382,
    tipo: "soy-starken",
    estado: "abierto",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 4304 4750",
  },
  {
    id: "br-118",
    nombre: "Starken Puerto Montt 1",
    direccion: "Av. Principal 898, Puerto Montt",
    comuna: "Puerto Montt",
    region: "Regiones",
    lat: -41.4731,
    lng: -72.9598,
    tipo: "red-alianzas",
    estado: "cerrado",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 1526 4171",
  },
  {
    id: "br-119",
    nombre: "Starken Puerto Montt 2",
    direccion: "Av. Principal 482, Puerto Montt",
    comuna: "Puerto Montt",
    region: "Regiones",
    lat: -41.4502,
    lng: -72.9525,
    tipo: "24/7",
    estado: "cerrado",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 8435 4311",
  },
  {
    id: "br-120",
    nombre: "Starken Puerto Montt 3",
    direccion: "Av. Principal 763, Puerto Montt",
    comuna: "Puerto Montt",
    region: "Regiones",
    lat: -41.4832,
    lng: -72.9245,
    tipo: "red-alianzas",
    estado: "con_retraso",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 9016 5575",
  },
  {
    id: "br-121",
    nombre: "Starken Providencia 12",
    direccion: "Av. Principal 8578, Providencia",
    comuna: "Providencia",
    region: "Región Metropolitana",
    lat: -33.4127,
    lng: -70.6273,
    tipo: "24/7",
    estado: "cerrado",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 6659 8003",
  },
  {
    id: "br-122",
    nombre: "Starken Las Condes 12",
    direccion: "Av. Principal 1246, Las Condes",
    comuna: "Las Condes",
    region: "Región Metropolitana",
    lat: -33.3986,
    lng: -70.5506,
    tipo: "soy-starken",
    estado: "abierto",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 9031 6340",
  },
  {
    id: "br-123",
    nombre: "Starken Vitacura 12",
    direccion: "Av. Principal 5094, Vitacura",
    comuna: "Vitacura",
    region: "Región Metropolitana",
    lat: -33.3755,
    lng: -70.5808,
    tipo: "red-alianzas",
    estado: "cerrado",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 5333 5977",
  },
  {
    id: "br-124",
    nombre: "Starken Ñuñoa 12",
    direccion: "Av. Principal 742, Ñuñoa",
    comuna: "Ñuñoa",
    region: "Región Metropolitana",
    lat: -33.4628,
    lng: -70.5932,
    tipo: "tradicional",
    estado: "abierto",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 1668 5026",
  },
  {
    id: "br-125",
    nombre: "Starken La Florida 12",
    direccion: "Av. Principal 1030, La Florida",
    comuna: "La Florida",
    region: "Región Metropolitana",
    lat: -33.5325,
    lng: -70.5992,
    tipo: "24/7",
    estado: "cerrado",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 4789 1309",
  },
  {
    id: "br-126",
    nombre: "Starken Puente Alto 12",
    direccion: "Av. Principal 3504, Puente Alto",
    comuna: "Puente Alto",
    region: "Región Metropolitana",
    lat: -33.6196,
    lng: -70.5749,
    tipo: "soy-starken",
    estado: "abierto",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 2758 3510",
  },
  {
    id: "br-127",
    nombre: "Starken Maipú 12",
    direccion: "Av. Principal 3342, Maipú",
    comuna: "Maipú",
    region: "Región Metropolitana",
    lat: -33.5040,
    lng: -70.7562,
    tipo: "red-alianzas",
    estado: "cerrado",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 6622 3028",
  },
  {
    id: "br-128",
    nombre: "Starken San Miguel 12",
    direccion: "Av. Principal 2340, San Miguel",
    comuna: "San Miguel",
    region: "Región Metropolitana",
    lat: -33.4954,
    lng: -70.6545,
    tipo: "tradicional",
    estado: "abierto",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 9353 1296",
  },
  {
    id: "br-129",
    nombre: "Starken Peñalolén 12",
    direccion: "Av. Principal 4948, Peñalolén",
    comuna: "Peñalolén",
    region: "Región Metropolitana",
    lat: -33.4786,
    lng: -70.5387,
    tipo: "24/7",
    estado: "cerrado",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 4559 2788",
  },
  {
    id: "br-130",
    nombre: "Starken Pudahuel 13",
    direccion: "Av. Principal 313, Pudahuel",
    comuna: "Pudahuel",
    region: "Región Metropolitana",
    lat: -33.4323,
    lng: -70.7619,
    tipo: "soy-starken",
    estado: "abierto",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 8040 2165",
  },
  {
    id: "br-131",
    nombre: "Starken Recoleta 13",
    direccion: "Av. Principal 4046, Recoleta",
    comuna: "Recoleta",
    region: "Región Metropolitana",
    lat: -33.4082,
    lng: -70.6364,
    tipo: "red-alianzas",
    estado: "cerrado",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 1214 1182",
  },
  {
    id: "br-132",
    nombre: "Starken Lo Barnechea 13",
    direccion: "Av. Principal 2772, Lo Barnechea",
    comuna: "Lo Barnechea",
    region: "Región Metropolitana",
    lat: -33.3509,
    lng: -70.5011,
    tipo: "tradicional",
    estado: "abierto",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 5283 8881",
  },
  {
    id: "br-133",
    nombre: "Starken La Reina 13",
    direccion: "Av. Principal 4117, La Reina",
    comuna: "La Reina",
    region: "Región Metropolitana",
    lat: -33.4300,
    lng: -70.5484,
    tipo: "24/7",
    estado: "cerrado",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 6319 5758",
  },
  {
    id: "br-134",
    nombre: "Starken San Bernardo 13",
    direccion: "Av. Principal 8388, San Bernardo",
    comuna: "San Bernardo",
    region: "Región Metropolitana",
    lat: -33.5817,
    lng: -70.6973,
    tipo: "soy-starken",
    estado: "abierto",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 4925 4288",
  },
  {
    id: "br-135",
    nombre: "Starken Santiago Centro 13",
    direccion: "Av. Principal 3275, Santiago Centro",
    comuna: "Santiago Centro",
    region: "Región Metropolitana",
    lat: -33.4377,
    lng: -70.6665,
    tipo: "red-alianzas",
    estado: "cerrado",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 8551 6201",
  },
  {
    id: "br-136",
    nombre: "Starken Providencia 13",
    direccion: "Av. Principal 2232, Providencia",
    comuna: "Providencia",
    region: "Región Metropolitana",
    lat: -33.4136,
    lng: -70.6196,
    tipo: "tradicional",
    estado: "abierto",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 5602 5952",
  },
  {
    id: "br-137",
    nombre: "Starken Las Condes 13",
    direccion: "Av. Principal 1484, Las Condes",
    comuna: "Las Condes",
    region: "Región Metropolitana",
    lat: -33.3980,
    lng: -70.5776,
    tipo: "24/7",
    estado: "cerrado",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 7199 1389",
  },
  {
    id: "br-138",
    nombre: "Starken Vitacura 13",
    direccion: "Av. Principal 2934, Vitacura",
    comuna: "Vitacura",
    region: "Región Metropolitana",
    lat: -33.3857,
    lng: -70.5623,
    tipo: "soy-starken",
    estado: "abierto",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 8355 6023",
  },
  {
    id: "br-139",
    nombre: "Starken Ñuñoa 13",
    direccion: "Av. Principal 7585, Ñuñoa",
    comuna: "Ñuñoa",
    region: "Región Metropolitana",
    lat: -33.4406,
    lng: -70.5997,
    tipo: "red-alianzas",
    estado: "cerrado",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 5825 2651",
  },
  {
    id: "br-140",
    nombre: "Starken La Florida 14",
    direccion: "Av. Principal 6024, La Florida",
    comuna: "La Florida",
    region: "Región Metropolitana",
    lat: -33.5153,
    lng: -70.5606,
    tipo: "tradicional",
    estado: "abierto",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 9438 1366",
  },
  {
    id: "br-141",
    nombre: "Starken Puente Alto 14",
    direccion: "Av. Principal 2992, Puente Alto",
    comuna: "Puente Alto",
    region: "Región Metropolitana",
    lat: -33.5822,
    lng: -70.5774,
    tipo: "24/7",
    estado: "cerrado",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 9706 3213",
  },
  {
    id: "br-142",
    nombre: "Starken Maipú 14",
    direccion: "Av. Principal 3962, Maipú",
    comuna: "Maipú",
    region: "Región Metropolitana",
    lat: -33.4993,
    lng: -70.7529,
    tipo: "soy-starken",
    estado: "abierto",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 1319 2098",
  },
  {
    id: "br-143",
    nombre: "Starken San Miguel 14",
    direccion: "Av. Principal 9034, San Miguel",
    comuna: "San Miguel",
    region: "Región Metropolitana",
    lat: -33.4885,
    lng: -70.6599,
    tipo: "red-alianzas",
    estado: "cerrado",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 9774 6363",
  },
  {
    id: "br-144",
    nombre: "Starken Peñalolén 14",
    direccion: "Av. Principal 6099, Peñalolén",
    comuna: "Peñalolén",
    region: "Región Metropolitana",
    lat: -33.4776,
    lng: -70.5562,
    tipo: "tradicional",
    estado: "abierto",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 2734 8618",
  },
  {
    id: "br-145",
    nombre: "Starken Pudahuel 14",
    direccion: "Av. Principal 3094, Pudahuel",
    comuna: "Pudahuel",
    region: "Región Metropolitana",
    lat: -33.4221,
    lng: -70.7553,
    tipo: "24/7",
    estado: "cerrado",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 5702 7178",
  },
  {
    id: "br-146",
    nombre: "Starken Recoleta 14",
    direccion: "Av. Principal 8249, Recoleta",
    comuna: "Recoleta",
    region: "Región Metropolitana",
    lat: -33.3928,
    lng: -70.6373,
    tipo: "soy-starken",
    estado: "abierto",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 9114 8336",
  },
  {
    id: "br-147",
    nombre: "Starken Lo Barnechea 14",
    direccion: "Av. Principal 6528, Lo Barnechea",
    comuna: "Lo Barnechea",
    region: "Región Metropolitana",
    lat: -33.3488,
    lng: -70.4830,
    tipo: "red-alianzas",
    estado: "cerrado",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 8088 8637",
  },
  {
    id: "br-148",
    nombre: "Starken La Reina 14",
    direccion: "Av. Principal 4066, La Reina",
    comuna: "La Reina",
    region: "Región Metropolitana",
    lat: -33.4327,
    lng: -70.5610,
    tipo: "tradicional",
    estado: "abierto",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 3602 8157",
  },
  {
    id: "br-149",
    nombre: "Starken San Bernardo 14",
    direccion: "Av. Principal 1372, San Bernardo",
    comuna: "San Bernardo",
    region: "Región Metropolitana",
    lat: -33.5872,
    lng: -70.7056,
    tipo: "24/7",
    estado: "cerrado",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 8414 4967",
  },
  {
    id: "br-150",
    nombre: "Starken Santiago Centro 15",
    direccion: "Av. Principal 1167, Santiago Centro",
    comuna: "Santiago Centro",
    region: "Región Metropolitana",
    lat: -33.4499,
    lng: -70.6657,
    tipo: "soy-starken",
    estado: "abierto",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 7302 5694",
  },
  {
    id: "br-151",
    nombre: "Starken Providencia 15",
    direccion: "Av. Principal 7553, Providencia",
    comuna: "Providencia",
    region: "Región Metropolitana",
    lat: -33.4148,
    lng: -70.6174,
    tipo: "red-alianzas",
    estado: "cerrado",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 3013 1539",
  },
  {
    id: "br-152",
    nombre: "Starken Las Condes 15",
    direccion: "Av. Principal 863, Las Condes",
    comuna: "Las Condes",
    region: "Región Metropolitana",
    lat: -33.4010,
    lng: -70.5342,
    tipo: "tradicional",
    estado: "abierto",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 8467 9177",
  },
  {
    id: "br-153",
    nombre: "Starken Vitacura 15",
    direccion: "Av. Principal 885, Vitacura",
    comuna: "Vitacura",
    region: "Región Metropolitana",
    lat: -33.3715,
    lng: -70.5853,
    tipo: "24/7",
    estado: "cerrado",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 8048 9405",
  },
  {
    id: "br-154",
    nombre: "Starken Ñuñoa 15",
    direccion: "Av. Principal 2633, Ñuñoa",
    comuna: "Ñuñoa",
    region: "Región Metropolitana",
    lat: -33.4659,
    lng: -70.5998,
    tipo: "soy-starken",
    estado: "abierto",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 5338 9794",
  },
  {
    id: "br-155",
    nombre: "Starken La Florida 15",
    direccion: "Av. Principal 4181, La Florida",
    comuna: "La Florida",
    region: "Región Metropolitana",
    lat: -33.5198,
    lng: -70.5877,
    tipo: "red-alianzas",
    estado: "cerrado",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 1425 4778",
  },
  {
    id: "br-156",
    nombre: "Starken Puente Alto 15",
    direccion: "Av. Principal 639, Puente Alto",
    comuna: "Puente Alto",
    region: "Región Metropolitana",
    lat: -33.6174,
    lng: -70.5746,
    tipo: "tradicional",
    estado: "abierto",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 5765 5123",
  },
  {
    id: "br-157",
    nombre: "Starken Maipú 15",
    direccion: "Av. Principal 4134, Maipú",
    comuna: "Maipú",
    region: "Región Metropolitana",
    lat: -33.5048,
    lng: -70.7476,
    tipo: "24/7",
    estado: "cerrado",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 1848 2713",
  },
  {
    id: "br-158",
    nombre: "Starken San Miguel 15",
    direccion: "Av. Principal 6638, San Miguel",
    comuna: "San Miguel",
    region: "Región Metropolitana",
    lat: -33.4907,
    lng: -70.6416,
    tipo: "soy-starken",
    estado: "abierto",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 3334 8029",
  },
  {
    id: "br-159",
    nombre: "Starken Peñalolén 15",
    direccion: "Av. Principal 6797, Peñalolén",
    comuna: "Peñalolén",
    region: "Región Metropolitana",
    lat: -33.4834,
    lng: -70.5655,
    tipo: "red-alianzas",
    estado: "cerrado",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 5845 9023",
  },
  {
    id: "br-160",
    nombre: "Starken Pudahuel 16",
    direccion: "Av. Principal 5132, Pudahuel",
    comuna: "Pudahuel",
    region: "Región Metropolitana",
    lat: -33.4239,
    lng: -70.7326,
    tipo: "tradicional",
    estado: "abierto",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 9674 8986",
  },
  {
    id: "br-161",
    nombre: "Starken Recoleta 16",
    direccion: "Av. Principal 6366, Recoleta",
    comuna: "Recoleta",
    region: "Región Metropolitana",
    lat: -33.3956,
    lng: -70.6301,
    tipo: "24/7",
    estado: "cerrado",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 2705 8115",
  },
  {
    id: "br-162",
    nombre: "Starken Lo Barnechea 16",
    direccion: "Av. Principal 7467, Lo Barnechea",
    comuna: "Lo Barnechea",
    region: "Región Metropolitana",
    lat: -33.3589,
    lng: -70.4812,
    tipo: "soy-starken",
    estado: "abierto",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 2669 1401",
  },
  {
    id: "br-163",
    nombre: "Starken La Reina 16",
    direccion: "Av. Principal 9277, La Reina",
    comuna: "La Reina",
    region: "Región Metropolitana",
    lat: -33.4299,
    lng: -70.5386,
    tipo: "red-alianzas",
    estado: "cerrado",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 3070 2330",
  },
  {
    id: "br-164",
    nombre: "Starken San Bernardo 16",
    direccion: "Av. Principal 3034, San Bernardo",
    comuna: "San Bernardo",
    region: "Región Metropolitana",
    lat: -33.6057,
    lng: -70.6967,
    tipo: "tradicional",
    estado: "abierto",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 2492 3848",
  },
  {
    id: "br-165",
    nombre: "Starken Santiago Centro 16",
    direccion: "Av. Principal 8253, Santiago Centro",
    comuna: "Santiago Centro",
    region: "Región Metropolitana",
    lat: -33.4387,
    lng: -70.6546,
    tipo: "24/7",
    estado: "cerrado",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 2576 8366",
  },
  {
    id: "br-166",
    nombre: "Starken Providencia 16",
    direccion: "Av. Principal 4797, Providencia",
    comuna: "Providencia",
    region: "Región Metropolitana",
    lat: -33.4267,
    lng: -70.6224,
    tipo: "soy-starken",
    estado: "abierto",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 3557 4974",
  },
  {
    id: "br-167",
    nombre: "Starken Las Condes 16",
    direccion: "Av. Principal 6944, Las Condes",
    comuna: "Las Condes",
    region: "Región Metropolitana",
    lat: -33.4072,
    lng: -70.5265,
    tipo: "red-alianzas",
    estado: "cerrado",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 4053 6468",
  },
  {
    id: "br-168",
    nombre: "Starken Vitacura 16",
    direccion: "Av. Principal 254, Vitacura",
    comuna: "Vitacura",
    region: "Región Metropolitana",
    lat: -33.3893,
    lng: -70.5544,
    tipo: "tradicional",
    estado: "abierto",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 1147 8737",
  },
  {
    id: "br-169",
    nombre: "Starken Ñuñoa 16",
    direccion: "Av. Principal 3302, Ñuñoa",
    comuna: "Ñuñoa",
    region: "Región Metropolitana",
    lat: -33.4592,
    lng: -70.5808,
    tipo: "24/7",
    estado: "cerrado",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 6212 2336",
  },
  {
    id: "br-170",
    nombre: "Starken La Florida 17",
    direccion: "Av. Principal 7412, La Florida",
    comuna: "La Florida",
    region: "Región Metropolitana",
    lat: -33.5319,
    lng: -70.5871,
    tipo: "soy-starken",
    estado: "abierto",
    horario: horarioEstandar,
    modalidades: ["Envío de paquetes", "Retiro", "Encomiendas"],
    dimensionesMax: "150 x 80 x 80 cm · hasta 50 kg",
    ultimoRetiro: "18:30",
    telefono: "+56 9 7358 3195",
  }]

export const comunasDisponibles = Array.from(new Set(sucursales.map((s) => s.comuna))).sort()
